import test from 'node:test';import assert from 'node:assert/strict';import {Game} from '../src/engine.js';import {LEVELS} from '../src/levels.js';import {SKILLS} from '../src/skills.js';import {objectPosition,isDangerous} from '../src/objects.js';
function scene(){const g=new Game();g.level={...g.level,objects:[],hazard:'water',exitX:950,exitY:100};g.terrain.fill(0);g.rect(20,300,960,170,1);g.spawned=20;g.stock=Object.fromEntries(Object.keys(SKILLS).map(k=>[k,20]));const u={id:0,x:100,y:300,dir:1,state:'walk',vy:0,jobTick:0};g.units=[u];return [g,u];}
test('each map has a distinct world and its supplied skills exist',()=>{assert.equal(new Set(LEVELS.map(l=>l.theme)).size,20);for(const l of LEVELS)for(const key of Object.keys(l.stock))assert.ok(SKILLS[key]);});
test('basher removes soft wall but never steel',()=>{for(const material of [1,2]){const [g,u]=scene();g.rect(108,265,30,35,material);g.assign(0,'bash');for(let i=0;i<130;i++)g.step();assert.equal(g.at(120,290),material===1?0:2);}});
test('miner digs a continuous descending tunnel',()=>{const [g,u]=scene();g.assign(0,'mine');for(let i=0;i<80;i++)g.step();assert.ok(u.x>120&&u.y>315);assert.equal(g.at(120,305),0);});
test('permanent parachute prevents a lethal fall without duplicate spending',()=>{const [g,u]=scene();u.y=100;u.state='fall';u.fallStart=100;assert.ok(g.assign(0,'float').ok);const stock=g.stock.float;assert.equal(g.assign(0,'float').ok,false);assert.equal(g.stock.float,stock);for(let i=0;i<260;i++)g.step();assert.equal(g.lost,0);assert.ok(g.units.includes(u));});
test('climber scales a wall and steps onto its top',()=>{const [g,u]=scene();g.rect(120,250,60,50,2);g.assign(0,'climb');for(let i=0;i<150;i++)g.step();assert.ok(u.x>125);assert.equal(u.y,250);});
test('platformer spans horizontally and stacker builds upward',()=>{for(const key of ['platform','stack']){const [g,u]=scene();g.assign(0,key);for(let i=0;i<192;i++)g.step();assert.ok(key==='platform'?u.x>190:g.at(100,264)===3);assert.equal(g.stock[key],19);}});
test('jump crosses a short pit',()=>{const [g,u]=scene();g.rect(105,300,70,170,0);g.assign(0,'jump');for(let i=0;i<85;i++)g.step();assert.equal(g.lost,0);assert.ok(u.x>175);});
test('runner moves faster and turner reverses direction',()=>{const [g,u]=scene();g.assign(0,'run');g.step();assert.ok(u.x>101);g.assign(0,'turn');assert.equal(u.dir,-1);});
test('attractor holds walkers until released',()=>{const [g,u]=scene();const w={...u,id:1,x:140};g.units.push(w);g.assign(0,'attract');g.step();assert.equal(w.x,140);g.assign(0,'walk');g.step();assert.ok(w.x>140);});
test('exploder sacrifices one lemming and respects steel',()=>{const [g,u]=scene();g.rect(100,280,8,15,2);g.assign(0,'explode');for(let i=0;i<180;i++)g.step();assert.equal(g.lost,1);assert.equal(g.at(103,285),2);assert.equal(g.at(90,304),0);});
test('swimmer survives water but not lava',()=>{for(const hazard of ['water','lava']){const [g,u]=scene();g.level.hazard=hazard;g.terrain.fill(0);u.y=442;u.state='fall';u.abilities={swim:true};g.step();assert.equal(g.lost,hazard==='water'?0:1);}});
test('ladders and poles transport walkers to their destination',()=>{for(const type of ['ladder','pole']){const [g,u]=scene();const target=type==='ladder'?240:360;g.level.objects=[{type,x:100,y:300,top:target,bottom:target,dir:1}];g.rect(105,target,100,5,1);for(let i=0;i<62;i++)g.step();assert.equal(u.state,'walk');assert.ok(u.x>=112);assert.equal(u.y,target);}});
test('trampoline launches and safely lands a walker',()=>{const [g,u]=scene();g.level.objects=[{type:'trampoline',x:95,y:300,w:20,dir:1}];g.step();assert.equal(u.state,'jump');for(let i=0;i<90;i++)g.step();assert.equal(g.lost,0);assert.ok(u.x>220);});
test('switch permanently disables its timed trap and reset restores it',()=>{const [g,u]=scene();g.level.objects=[{type:'switch',x:100,y:300,target:'press'}];g.step();assert.ok(g.disabledObjects.has('press'));assert.equal(isDangerous({id:'press',type:'crusher'},0,g.disabledObjects),false);g.reset();assert.equal(g.disabledObjects.size,0);});
test('shuttle has stationary boarding windows and reaches both banks',()=>{const o={type:'lift',x:275,y:300,toX:495,toY:300,w:60,period:720};assert.deepEqual(objectPosition(o,0),objectPosition(o,60));assert.equal(objectPosition(o,360).x,495);assert.equal(objectPosition(o,720).x,275);});
