import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {Game} from '../src/engine.js';import {CAMPAIGN,LEVELS} from '../src/levels.js';import {CREATURE_IDS,CREATURE_ROUTES} from '../src/creature-level-data.js';import {solveConnected} from './connected-solution.js';import {connectedCrossing} from '../src/connected-terrain.js';import {earnedStars} from '../src/progress.js';import {scenerySupported} from '../src/landscape-art.js';import {objectPosition} from '../src/objects.js';import {liftRails} from '../src/object-art.js';
for(const [i,id]of CREATURE_IDS.entries()){
 test(`${LEVELS[id].name}: every offered skill contributes to a complete three-star rescue`,()=>{const g=solveConnected(id);assert.equal(g.saved,g.level.total);assert.equal(g.lost,0);assert.equal(earnedStars(g.level,{completed:g.result==='win',saved:g.saved,lost:g.lost,ticks:g.tick}),3);for(const skill of Object.keys(g.level.stock))assert.ok(g.events.some(e=>e.skill===skill),skill);});
 test(`${LEVELS[id].name}: crossings are open, doors supported, and player intervention is required`,()=>{const g=new Game(id);for(const gap of CREATURE_ROUTES[i].gaps){const q=connectedCrossing(g.level,gap);assert.equal(g.at((q.x+q.right)/2,q.y),0);}for(const [x,y]of [[g.level.spawnX,g.level.spawnY],[g.level.exitX,g.level.exitY]])for(let dx=-18;dx<=18;dx++)assert.ok(g.at(x+dx,y),'door footing');for(let n=0;n<12000&&!g.result;n++)g.step();assert.ok(g.saved<g.level.target);});
}
test('Creature Comfort sources are recoverable but absent from the active campaign',()=>{assert.equal(CAMPAIGN.length,30);assert.ok(CREATURE_IDS.every(id=>!CAMPAIGN.some(l=>l.id===id)));assert.ok(CREATURE_IDS.every(id=>LEVELS[id].theme==='creature'));assert.equal(new Set(CREATURE_IDS.map(id=>createHash('sha256').update(new Game(id).terrain).digest('hex'))).size,10);});
test('scenery needs its complete footing and cannot hang from a narrow ledge',()=>{const level={terrain:[[90,100,20,12,1]],shapes:[]};assert.equal(scenerySupported(level,100,100,null,30,40),false);assert.equal(scenerySupported({terrain:[[40,100,120,12,1]],shapes:[]},100,100,null,30,40),true);});
test('both lift wheels remain on their own rails on diagonal as well as horizontal journeys',()=>{for(const o of [{type:'lift',x:100,y:200,toX:400,toY:300,w:80},{type:'lift',x:150,y:250,toX:500,toY:250,w:70}])for(let tick=0;tick<480;tick+=13){const p=objectPosition(o,tick);for(const rail of liftRails(o)){const [x,y]=rail.from,[xx,yy]=rail.to;assert.ok(Math.abs((p.x+rail.axle-x)*(yy-y)-(p.y+12-y)*(xx-x))<.001);}}});
